/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: yacinebel (https://sketchfab.com/yacinebel)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/space-ship-75443bb3a8914533afa350b742ad1fb0
title: Space Ship
*/
import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF, useScroll } from "@react-three/drei";
import gsap from "gsap";
import { useEffect } from "react";
import { useFrame } from "@react-three/fiber";
import { Float } from "./Image";
import { useThree } from "@react-three/fiber";
import { config, useSpring, a, easings } from "@react-spring/three";
import { useState } from "react";
import useAudio from "./../custom-Hooks/useAudio";

const ModelShip = ({
  speed = 1,
  amplitude = 1,
  inViewPageTwo,
  inViewPageThree,
  ...props
}) => {
  const { nodes, materials } = useGLTF("/scene.glb");
  const ref = useRef();
  const [hovered, setHover] = useState(false);
  const [playing, toggle] = useAudio(
    "https://res.cloudinary.com/dbqlsilt2/video/upload/v1660769289/a/https___voicebot.su_es_sound_sonido-de-funcionamiento-del-motor-de-la-nave-espacial__vimntt.mp3"
  );

  const { scroll, visible } = useScroll();
  const three = useThree();

  useFrame(() => {
    ref.current.rotation.x += 0.005;
    if (hovered) {
      ref.current.rotation.x += 0.1;
    }
  });

  const spring = useSpring({
    position: inViewPageTwo
      ? [0, -8.2, 1]
      : inViewPageThree
      ? [-2.2, -15.5, 1]
      : [1.6, 1.8, 1],
    rotation: inViewPageTwo
      ? [-Math.PI / 2, -0.9, -1.1]
      : inViewPageThree
      ? [Math.PI / 2, -4.5, -1.2]
      : [-Math.PI / 2, -1.5, -1.1],
    config: {
      mass: 1,
      tension: 200,
      friction: 50,
      precision: 0.0001,
      easing: easings.easeInOutQuart,
      loop: { reverse: true },
    },
  });

  console.log(spring.position, "meee");

  console.log(three.clock, "horeverd");
  return (
    <Float amplitude={0.3} speed={2}>
      <a.group
        ref={ref}
        onPointerOver={(e) => {
          setHover(true);
          toggle;
        }}
        onPointerOut={(e) => {
          setHover(false);
          toggle;
        }}
        onWheel={(e) => console.log("wheel spins")}
        dispose={null}
        position={spring.position}
        rotation={spring.rotation}
        {...props}
      >
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group scale={0.023}>
              <group position={[0, 0, 16.96]}>
                <mesh
                  geometry={nodes.Circle001_Material009_0.geometry}
                  material={materials["Material.009"]}
                />
              </group>
              <group position={[0, 0.24, 26.41]}>
                <mesh
                  geometry={nodes.Circle002_Material009_0.geometry}
                  material={materials["Material.009"]}
                />
              </group>
              <mesh
                geometry={nodes.Circle003_Material002_0.geometry}
                material={materials["Material.002"]}
              />
              <mesh
                geometry={nodes.Circle004_Material011_0.geometry}
                material={materials["Material.011"]}
              />
              <group position={[0, 0, 16.96]}>
                <mesh
                  geometry={nodes.Circle005_Material009_0.geometry}
                  material={materials["Material.009"]}
                />
              </group>
              <group position={[0, 0.24, 26.41]}>
                <mesh
                  geometry={nodes.Circle006_Material009_0.geometry}
                  material={materials["Material.009"]}
                />
              </group>
              <mesh
                geometry={nodes.Circle_Material007_0.geometry}
                material={materials["Material.007"]}
              />
            </group>
          </group>
        </group>
      </a.group>
    </Float>
  );
};

export default ModelShip;

useGLTF.preload("/scene.glb");
