/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';
import { useRef } from 'react';

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/dGNbuD2SPpLVaKfn/scene.splinecode')
  const ref = useRef();
  useFrame(() => {
    ref.current.rotation.y += 0.005;
  })
  
  return (
    <>
      <color attach="background" args={['#6e5597']} />
      <group ref={ref} {...props} dispose={null} position={[1.5, 0, 0]} scale={.0025} rotation={[0, -16, 0]}>
        <directionalLight
          name="Directional Light"
          castShadow
          intensity={2}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-near={-10000}
          shadow-camera-far={100000}
          shadow-camera-left={-500}
          shadow-camera-right={500}
          shadow-camera-top={500}
          shadow-camera-bottom={-500}
          color="#fe90fd"
          position={[0, 93.62, 2103.13]}
        />
        <pointLight
          name="Point Light"
          castShadow
          intensity={2}
          distance={2256}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-near={100}
          shadow-camera-far={100000}
          color="#00b3f5"
          position={[-1024.21, 974.49, -893.81]}
        />
        <mesh
          name="Sphere 6"
          geometry={nodes['Sphere 6'].geometry}
          material={materials['Sphere 6 Material']}
          castShadow
          receiveShadow
          position={[-632.19, 36.08, 839.02]}
        />
        <mesh
          name="Sphere 5"
          geometry={nodes['Sphere 5'].geometry}
          material={materials['Sphere 5 Material']}
          castShadow
          receiveShadow
          position={[-632.19, 36.08, 1282.4]}
        />
        <mesh
          name="Cube 61"
          geometry={nodes['Cube 61'].geometry}
          material={materials['Cube 61 Material']}
          castShadow
          receiveShadow
          position={[-551.65, 13.49, 1064.22]}
          scale={[0.35, 0.33, 0.89]}
        />
        <group name=" Coffee Cup" position={[-341.34, 10.44, 757.51]}>
          <mesh
            name="Torus"
            geometry={nodes.Torus.geometry}
            material={materials['Torus Material']}
            castShadow
            receiveShadow
            position={[-34.07, -3.08, 36]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <mesh
            name="Cylinder 11"
            geometry={nodes['Cylinder 11'].geometry}
            material={materials['Cylinder 11 Material']}
            castShadow
            receiveShadow
            position={[-35.99, -2.27, 3.73]}
            rotation={[0, Math.PI / 2, 0]}
            scale={[0.29, 0.52, 0.29]}
          />
        </group>
        <mesh
          name="Sphere 4"
          geometry={nodes['Sphere 4'].geometry}
          material={materials['Sphere 4 Material']}
          castShadow
          receiveShadow
          position={[237.1, 191.83, 277.22]}
        />
        <mesh
          name="Sphere 3"
          geometry={nodes['Sphere 3'].geometry}
          material={materials['Sphere 3 Material']}
          castShadow
          receiveShadow
          position={[912.87, 524.51, 675.57]}
        />
        <mesh
          name="Sphere 2"
          geometry={nodes['Sphere 2'].geometry}
          material={materials['Sphere 2 Material']}
          castShadow
          receiveShadow
          position={[602.84, 212.88, 484.65]}
        />
        <group
          name="picture-ui"
          position={[-1431.88, -1089.79, 5525.91]}
          rotation={[-Math.PI, 1.56, -Math.PI]}
          scale={0.71}
        >
          <mesh
            name="Triangle 2"
            geometry={nodes['Triangle 2'].geometry}
            material={materials['Triangle 2 Material']}
            castShadow
            receiveShadow
            position={[76.71, -42.67, 9.58]}
            scale={1.42}
          />
          <mesh
            name="Triangle"
            geometry={nodes.Triangle.geometry}
            material={materials['Triangle Material']}
            castShadow
            receiveShadow
            position={[-96.33, -21.16, 9.58]}
            scale={1.42}
          />
          <mesh
            name="Ellipse"
            geometry={nodes.Ellipse.geometry}
            material={materials['Ellipse Material']}
            castShadow
            receiveShadow
            position={[-14.73, 68.78, 9.58]}
            scale={1.42}
          />
          <mesh
            name="Rectangle 6"
            geometry={nodes['Rectangle 6'].geometry}
            material={materials['Rectangle 6 Material']}
            castShadow
            receiveShadow
            position={[-42, 0, -1.46]}
          />
          <mesh
            name="Rectangle 5"
            geometry={nodes['Rectangle 5'].geometry}
            material={materials['red-2']}
            castShadow
            receiveShadow
            position={[-38, 0, -17.88]}
          />
        </group>
        <group
          name="color-ui"
          position={[-1532.37, -898.68, 5787.58]}
          rotation={[-Math.PI, 1.56, -Math.PI]}
          scale={0.62}
        >
          <mesh
            name="Ellipse 3"
            geometry={nodes['Ellipse 3'].geometry}
            material={materials['red-1']}
            castShadow
            receiveShadow
            position={[-59.3, 308.03, 4.65]}
            scale={1.14}
          />
          <mesh
            name="Ellipse 2"
            geometry={nodes['Ellipse 2'].geometry}
            material={materials['red-1']}
            castShadow
            receiveShadow
            position={[-117.28, 308.03, 4.65]}
            scale={1.14}
          />
          <mesh
            name="Ellipse1"
            geometry={nodes.Ellipse1.geometry}
            material={materials['red-1']}
            castShadow
            receiveShadow
            position={[-177.11, 308.03, 4.65]}
            scale={1.14}
          />
          <mesh
            name="Rectangle 7"
            geometry={nodes['Rectangle 7'].geometry}
            material={materials['ui-color']}
            castShadow
            receiveShadow
            position={[0, -238.94, 4]}
          />
          <mesh
            name="Rectangle 9"
            geometry={nodes['Rectangle 9'].geometry}
            material={materials['red-3']}
            castShadow
            position={[98.23, -16.4, 3.27]}
          />
          <mesh
            name="Rectangle 8"
            geometry={nodes['Rectangle 8'].geometry}
            material={materials['red-3']}
            castShadow
            position={[98.23, 173.68, 3.27]}
          />
          <mesh
            name="Rectangle 91"
            geometry={nodes['Rectangle 91'].geometry}
            material={materials['red-3']}
            castShadow
            position={[-106.76, -16.4, 3.27]}
          />
          <mesh
            name="Rectangle 61"
            geometry={nodes['Rectangle 61'].geometry}
            material={materials['red-2']}
            castShadow
            position={[-106.76, 173.68, 3.27]}
          />
          <mesh
            name="Rectangle 51"
            geometry={nodes['Rectangle 51'].geometry}
            material={materials['Rectangle 51 Material']}
            castShadow
            receiveShadow
            position={[0, 0, -13.47]}
          />
        </group>
        <group
          name="text-ui"
          position={[-1618.27, -1084.93, 5418.83]}
          rotation={[-Math.PI, 1.56, -Math.PI]}
          scale={0.66}
        >
          <group name="Group 15" position={[381.08, 121.32, 18.33]} scale={1.01}>
            <mesh
              name="Cylinder 2"
              geometry={nodes['Cylinder 2'].geometry}
              material={materials['Cylinder 2 Material']}
              castShadow
              receiveShadow
              position={[-1.66, 133.57, 0.8]}
              rotation={[0, 0, -Math.PI / 2]}
            />
            <mesh
              name="Cylinder"
              geometry={nodes.Cylinder.geometry}
              material={materials['Cylinder Material']}
              castShadow
              receiveShadow
              position={[0.62, -133.57, 0.8]}
              rotation={[0, 0, Math.PI / 2]}
            />
            <mesh
              name="Sphere 21"
              geometry={nodes['Sphere 21'].geometry}
              material={materials['Sphere 21 Material']}
              castShadow
              receiveShadow
              position={[122.25, 132.87, 0]}
              rotation={[0, 0, -Math.PI / 2]}
            />
            <mesh
              name="Sphere"
              geometry={nodes.Sphere.geometry}
              material={materials['Sphere Material']}
              castShadow
              receiveShadow
              position={[-141.8, -132.87, 0]}
              rotation={[0, 0, Math.PI / 2]}
            />
            <mesh
              name="Cylinder 21"
              geometry={nodes['Cylinder 21'].geometry}
              material={materials['Cylinder 21 Material']}
              castShadow
              receiveShadow
              position={[123.29, 0.97, 0.8]}
              rotation={[0, 0, Math.PI]}
            />
            <mesh
              name="Cylinder1"
              geometry={nodes.Cylinder1.geometry}
              material={materials['Cylinder1 Material']}
              castShadow
              receiveShadow
              position={[-142.85, -0.97, 0.8]}
            />
            <mesh
              name="Sphere 22"
              geometry={nodes['Sphere 22'].geometry}
              material={materials['Sphere 22 Material']}
              castShadow
              receiveShadow
              position={[122.59, -132.87, 0]}
              rotation={[0, 0, Math.PI]}
            />
            <mesh
              name="Sphere1"
              geometry={nodes.Sphere1.geometry}
              material={materials['Sphere1 Material']}
              castShadow
              receiveShadow
              position={[-142.14, 132.87, 0]}
            />
          </group>
          <mesh
            name="Rectangle 4"
            geometry={nodes['Rectangle 4'].geometry}
            material={materials['red-1']}
            castShadow
            receiveShadow
            position={[369.97, -315.35, 5.68]}
            scale={1.52}
          />
          <mesh
            name="Rectangle 3"
            geometry={nodes['Rectangle 3'].geometry}
            material={materials['red-1']}
            castShadow
            receiveShadow
            position={[369.97, -225.14, 5.68]}
            scale={1.52}
          />
          <mesh
            name="Rectangle 2"
            geometry={nodes['Rectangle 2'].geometry}
            material={materials['red-1']}
            castShadow
            receiveShadow
            position={[410.36, -135.84, 5.68]}
            scale={1.52}
          />
          <group name="Text" position={[372.71, 159.53, 22.45]} scale={1.52}>
            <mesh
              name="A"
              geometry={nodes.A.geometry}
              material={materials['red-1']}
              castShadow
              receiveShadow
              position={[-77, -67.5, 0]}
            />
            <mesh
              name="a"
              geometry={nodes.a.geometry}
              material={materials['red-1']}
              castShadow
              receiveShadow
              position={[3.91, -67.5, 0]}
            />
          </group>
          <mesh
            name="Rectangle 52"
            geometry={nodes['Rectangle 52'].geometry}
            material={materials['Rectangle 52 Material']}
            castShadow
            position={[-180.73, -40.12, 19.4]}
          />
          <mesh
            name="Rectangle 31"
            geometry={nodes['Rectangle 31'].geometry}
            material={materials['Rectangle 31 Material']}
            castShadow
            receiveShadow
            position={[0, -44, 5.66]}
          />
          <mesh
            name="Rectangle 21"
            geometry={nodes['Rectangle 21'].geometry}
            material={materials['Rectangle 21 Material']}
            castShadow
            receiveShadow
            position={[0, 0, -23.62]}
          />
        </group>
        <group name="artboard-2" position={[5157.4, 392.06, 3722.48]} rotation={[-0.27, -0.27, -0.03]}>
          <group name="画" position={[-2.45, 124.23, 31.49]} rotation={[0.26, 0, 0]}>
            <mesh
              name="Shape 8"
              geometry={nodes['Shape 8'].geometry}
              material={materials['Shape 8 Material']}
              castShadow
              receiveShadow
              position={[78.91, -222.98, 65.09]}
              rotation={[-0.26, 0, 0]}
              scale={0.95}
            />
            <mesh
              name="Shape 7"
              geometry={nodes['Shape 7'].geometry}
              material={materials['Shape 7 Material']}
              castShadow
              receiveShadow
              position={[160.24, 193.09, -50.27]}
              rotation={[-0.26, 0, 0]}
              scale={0.95}
            />
            <mesh
              name="Shape 6"
              geometry={nodes['Shape 6'].geometry}
              material={materials['Shape 6 Material']}
              castShadow
              receiveShadow
              position={[105.3, 217.95, -51.78]}
              rotation={[-0.26, 0, 0]}
              scale={0.95}
            />
            <mesh
              name="Shape 5"
              geometry={nodes['Shape 5'].geometry}
              material={materials['Shape 5 Material']}
              castShadow
              receiveShadow
              position={[-165.44, -26.03, 8.16]}
              rotation={[-0.26, 0, 0]}
              scale={0.95}
            />
            <mesh
              name="Shape 3"
              geometry={nodes['Shape 3'].geometry}
              material={materials['Shape 3 Material']}
              castShadow
              receiveShadow
              position={[-164.1, -59.18, 17.48]}
              rotation={[-0.26, 0, 0]}
              scale={0.95}
            />
            <mesh
              name="Shape 2"
              geometry={nodes['Shape 2'].geometry}
              material={materials.green}
              castShadow
              receiveShadow
              position={[-164.35, -59.81, 18.46]}
              rotation={[-0.26, 0, 0]}
              scale={0.95}
            />
            <mesh
              name="Shape"
              geometry={nodes.Shape.geometry}
              material={materials['Shape Material']}
              castShadow
              receiveShadow
              position={[-163.83, -120.71, 36.17]}
              rotation={[-0.26, 0, 0]}
              scale={0.95}
            />
            <mesh
              name="Rectangle 22"
              geometry={nodes['Rectangle 22'].geometry}
              material={materials['red-2']}
              castShadow
              receiveShadow
              position={[0, 0, -0.05]}
              rotation={[-0.26, 0, -Math.PI / 2]}
              scale={0.95}
            />
            <mesh
              name="Rectangle"
              geometry={nodes.Rectangle.geometry}
              material={materials['Rectangle Material']}
              castShadow
              receiveShadow
              position={[0, 0, 0.53]}
              rotation={[-0.26, 0, -Math.PI / 2]}
              scale={0.95}
            />
          </group>
          <mesh
            name="Cube 5"
            geometry={nodes['Cube 5'].geometry}
            material={materials['red-3']}
            castShadow
            receiveShadow
            position={[-1, 125.37, 14.49]}
            rotation={[0, 0, -Math.PI / 2]}
          />
          <mesh
            name="Cube 6"
            geometry={nodes['Cube 6'].geometry}
            material={materials['artboard-ao']}
            castShadow
            receiveShadow
            position={[2.49, -110.74, -215.13]}
            rotation={[Math.PI / 6, 0, -Math.PI / 2]}
          />
          <mesh
            name="Cube 4"
            geometry={nodes['Cube 4'].geometry}
            material={materials['red-4']}
            castShadow
            receiveShadow
            position={[2.49, -180.05, 19.57]}
          />
          <mesh
            name="Cube 3"
            geometry={nodes['Cube 3'].geometry}
            material={materials['red-4']}
            castShadow
            receiveShadow
            position={[2.49, 164.41, -19.57]}
            rotation={[0, 0, -Math.PI / 2]}
          />
          <mesh
            name="Cube 2"
            geometry={nodes['Cube 2'].geometry}
            material={materials['artboard-ao']}
            castShadow
            receiveShadow
            position={[118.68, -139.91, -19.57]}
            rotation={[0, 0, -1.4]}
          />
          <mesh
            name="Cube"
            geometry={nodes.Cube.geometry}
            material={materials['artboard-ao']}
            castShadow
            receiveShadow
            position={[-107.2, -134.71, -19.57]}
            rotation={[0, 0, -1.75]}
          />
        </group>
        <mesh
          name="aro 2"
          geometry={nodes['aro 2'].geometry}
          material={materials['artboard-ao']}
          castShadow
          receiveShadow
          position={[-1346.73, 215.03, 1033.72]}
          rotation={[-1.5, -0.61, -1.73]}
          scale={[1, 1, 0.45]}
        />
        <mesh
          name="aro"
          geometry={nodes.aro.geometry}
          material={materials['artboard-ao']}
          castShadow
          receiveShadow
          position={[-1346.73, 215.03, 1033.72]}
          rotation={[-1.35, 0.43, -1.72]}
          scale={[1, 1, 0.45]}
        />
        <group name="Desktop" position={[-575.88, -116.29, 1059.02]}>
          <mesh
            name="Cylinder 3"
            geometry={nodes['Cylinder 3'].geometry}
            material={materials.stone_detail}
            castShadow
            receiveShadow
            position={[94.43, -9.22, -227.94]}
            scale={[0.11, 1.97, 0.11]}
          />
          <mesh
            name="Cylinder 31"
            geometry={nodes['Cylinder 31'].geometry}
            material={materials.stone_detail}
            castShadow
            receiveShadow
            position={[-95.92, -9.22, -227.94]}
            scale={[0.11, 1.97, 0.11]}
          />
          <mesh
            name="Cylinder 22"
            geometry={nodes['Cylinder 22'].geometry}
            material={materials.stone_detail}
            castShadow
            receiveShadow
            position={[94.43, -9.22, 225.06]}
            scale={[0.11, 1.97, 0.11]}
          />
          <mesh
            name="Cylinder2"
            geometry={nodes.Cylinder2.geometry}
            material={materials.stone_detail}
            castShadow
            receiveShadow
            position={[-95.92, -9.22, 225.06]}
            scale={[0.11, 1.97, 0.11]}
          />
          <mesh
            name="Cube 611"
            geometry={nodes['Cube 611'].geometry}
            material={materials.stairs}
            castShadow
            receiveShadow
            position={[0, 117.37, 0]}
          />
        </group>
        <mesh
          name="Sphere2"
          geometry={nodes.Sphere2.geometry}
          material={materials['Sphere2 Material']}
          castShadow
          receiveShadow
          position={[-1355, 227.98, 1034.41]}
        />
        <group name="plants" position={[-426.28, -221.51, 1073]} scale={0.35}>
          <mesh
            name="Cube 74"
            geometry={nodes['Cube 74'].geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[-660.7, -36.02, -642.74]}
            rotation={[-1.26, 0.26, -0.85]}
            scale={[0.11, 0.05, 0]}
          />
          <mesh
            name="Cube 73"
            geometry={nodes['Cube 73'].geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[-651.52, -40.21, -622.66]}
            rotation={[-1.44, 0.11, 1.09]}
            scale={[0.11, 0.05, 0.01]}
          />
          <mesh
            name="Cube 72"
            geometry={nodes['Cube 72'].geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[-639.3, -39.54, -641.64]}
            rotation={[-1.21, -0.18, -2.56]}
            scale={[0.1, 0.05, 0.01]}
          />
          <mesh
            name="Cube 741"
            geometry={nodes['Cube 741'].geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[-859.82, -33.84, -918.06]}
            rotation={[-1.12, 0.21, -1.34]}
            scale={[0.14, 0.07, 0.01]}
          />
          <mesh
            name="Cube 731"
            geometry={nodes['Cube 731'].geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[-864.33, -38.13, -888.24]}
            rotation={[-1.65, 0.33, 0.92]}
            scale={[0.14, 0.07, 0.01]}
          />
          <mesh
            name="Cube 721"
            geometry={nodes['Cube 721'].geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[-837.14, -41.86, -902.16]}
            rotation={[-1.32, -0.08, -3.14]}
            scale={[0.14, 0.07, 0.01]}
          />
          <mesh
            name="Cube 742"
            geometry={nodes['Cube 742'].geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[733.24, 48.34, -968.06]}
            rotation={[-1.53, 0.27, 1.08]}
            scale={[0.12, 0.06, 0]}
          />
          <mesh
            name="Cube 732"
            geometry={nodes['Cube 732'].geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[752.54, 48.55, -976.37]}
            rotation={[-1.24, -0.25, 2.77]}
            scale={[0.12, 0.06, 0.01]}
          />
          <mesh
            name="Cube 75"
            geometry={nodes['Cube 75'].geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[731.56, 52.07, -997.71]}
            rotation={[-1.23, 0.1, -1.15]}
            scale={[0.12, 0.06, 0]}
          />
          <mesh
            name="Cube 743"
            geometry={nodes['Cube 743'].geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[749.41, 49.3, -995.31]}
            rotation={[-1.23, 0.1, -2.28]}
            scale={[0.12, 0.06, 0]}
          />
          <mesh
            name="Cube 722"
            geometry={nodes['Cube 722'].geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[723.48, 50.36, -982.25]}
            rotation={[-1.2, 0.28, -0.05]}
            scale={[0.11, 0.06, 0.01]}
          />
          <mesh
            name="Cube 744"
            geometry={nodes['Cube 744'].geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[856.82, -32.39, -666.25]}
            rotation={[-1.59, -0.31, -2.79]}
            scale={[0.18, 0.08, 0.01]}
          />
          <mesh
            name="Cube 733"
            geometry={nodes['Cube 733'].geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[829.48, -31.66, -680.23]}
            rotation={[-1.5, 0.46, -1.63]}
            scale={[0.18, 0.09, 0.01]}
          />
          <mesh
            name="Cube 751"
            geometry={nodes['Cube 751'].geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[824.91, -39.35, -637.04]}
            rotation={[-1.56, 0.11, 1.05]}
            scale={[0.17, 0.08, 0.01]}
          />
          <mesh
            name="Cube 745"
            geometry={nodes['Cube 745'].geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[811.3, -39.68, -659.99]}
            rotation={[-1.61, 0.09, -0.02]}
            scale={[0.17, 0.09, 0.01]}
          />
          <mesh
            name="Cube 723"
            geometry={nodes['Cube 723'].geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[849.91, -37.21, -642.3]}
            rotation={[-1.8, -0.06, 2.24]}
            scale={[0.17, 0.08, 0.01]}
          />
          <mesh
            name="Cube 746"
            geometry={nodes['Cube 746'].geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[679.27, -34.66, -79.67]}
            rotation={[-1.35, 0.13, -0.82]}
            scale={[0.2, 0.1, 0.01]}
          />
          <mesh
            name="Cube 734"
            geometry={nodes['Cube 734'].geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[682.78, -35.39, -43.9]}
            rotation={[-1.91, 0.02, 0.76]}
            scale={[0.21, 0.1, 0.01]}
          />
          <mesh
            name="Cube 752"
            geometry={nodes['Cube 752'].geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[728.77, -37.94, -67.03]}
            rotation={[-1.57, -0.16, -3.01]}
            scale={[0.2, 0.1, 0.01]}
          />
          <mesh
            name="Cube 747"
            geometry={nodes['Cube 747'].geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[714.92, -40.4, -39.21]}
            rotation={[-1.57, -0.16, 2.14]}
            scale={[0.2, 0.1, 0.01]}
          />
          <mesh
            name="Cube 724"
            geometry={nodes['Cube 724'].geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[707.59, -36.56, -88.22]}
            rotation={[-1.37, -0.23, -1.84]}
            scale={[0.2, 0.1, 0.01]}
          />
          <mesh
            name="Cube 748"
            geometry={nodes['Cube 748'].geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[-417.65, -35.73, -253.56]}
            rotation={[-1.49, 0.21, -0.2]}
            scale={[0.18, 0.08, 0.01]}
          />
          <mesh
            name="Cube 735"
            geometry={nodes['Cube 735'].geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[-398.83, -42.02, -229.91]}
            rotation={[-1.54, -0.02, 1.37]}
            scale={[0.17, 0.09, 0.01]}
          />
          <mesh
            name="Cube 753"
            geometry={nodes['Cube 753'].geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[-374.8, -38.35, -268.86]}
            rotation={[-1.55, -0.19, -2.52]}
            scale={[0.17, 0.08, 0.01]}
          />
          <mesh
            name="Cube 749"
            geometry={nodes['Cube 749'].geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[-371.09, -39.01, -241.88]}
            rotation={[-1.51, -0.17, 2.73]}
            scale={[0.19, 0.08, 0.01]}
          />
          <mesh
            name="Cube 725"
            geometry={nodes['Cube 725'].geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[-401.66, -37.67, -278.76]}
            rotation={[-1.35, -0.08, -1.35]}
            scale={[0.21, 0.09, 0.01]}
          />
          <mesh
            name="Cube 7410"
            geometry={nodes['Cube 7410'].geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[-656.32, -40.96, 886.35]}
            rotation={[-1.38, 0.08, -0.17]}
            scale={[0.37, 0.2, 0.02]}
          />
          <mesh
            name="Cube 736"
            geometry={nodes['Cube 736'].geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[-622.39, -32.92, 948.07]}
            rotation={[-1.77, 0.09, 1.31]}
            scale={[0.42, 0.2, 0.02]}
          />
          <mesh
            name="Cube 754"
            geometry={nodes['Cube 754'].geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[-562.56, -38.87, 871.5]}
            rotation={[-1.44, -0.02, -2.62]}
            scale={[0.37, 0.21, 0.02]}
          />
          <mesh
            name="Cube 7411"
            geometry={nodes['Cube 7411'].geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[-566.17, -50.96, 934.28]}
            rotation={[-1.44, -0.05, 2.54]}
            scale={[0.4, 0.19, 0.02]}
          />
          <mesh
            name="Cube 726"
            geometry={nodes['Cube 726'].geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[-613.54, -26.24, 844.91]}
            rotation={[-1.12, -0.01, -1.49]}
            scale={[0.41, 0.18, 0.02]}
          />
          <mesh
            name="Cube 7412"
            geometry={nodes['Cube 7412'].geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[569.6, -45.54, 819.64]}
            rotation={[-1.39, 0.2, 1.12]}
            scale={[0.37, 0.2, 0.02]}
          />
          <mesh
            name="Cube 737"
            geometry={nodes['Cube 737'].geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[636.53, -32.27, 800.32]}
            rotation={[-1.34, -0.18, 2.68]}
            scale={[0.42, 0.2, 0.02]}
          />
          <mesh
            name="Cube 755"
            geometry={nodes['Cube 755'].geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[574.06, -32.58, 725.66]}
            rotation={[-1.4, 0.15, -1.35]}
            scale={[0.37, 0.21, 0.02]}
          />
          <mesh
            name="Cube 7413"
            geometry={nodes['Cube 7413'].geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[635.24, -43.76, 740.83]}
            rotation={[-1.33, 0.08, -2.4]}
            scale={[0.4, 0.19, 0.02]}
          />
          <mesh
            name="Cube 727"
            geometry={nodes['Cube 727'].geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[537.15, -26.64, 771.1]}
            rotation={[-1.34, 0.33, -0.24]}
            scale={[0.41, 0.18, 0.02]}
          />
          <mesh
            name="Cube 7414"
            geometry={nodes['Cube 7414'].geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[-767.11, -34.03, -672.91]}
            rotation={[-1.35, 0.13, -0.82]}
            scale={[0.2, 0.1, 0.01]}
          />
          <mesh
            name="Cube 738"
            geometry={nodes['Cube 738'].geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[-763.6, -34.75, -637.14]}
            rotation={[-1.91, 0.02, 0.76]}
            scale={[0.21, 0.1, 0.01]}
          />
          <mesh
            name="Cube 756"
            geometry={nodes['Cube 756'].geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[-717.61, -37.31, -660.28]}
            rotation={[-1.57, -0.16, -3.01]}
            scale={[0.2, 0.1, 0.01]}
          />
          <mesh
            name="Cube 7415"
            geometry={nodes['Cube 7415'].geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[-731.46, -39.77, -632.46]}
            rotation={[-1.57, -0.16, 2.14]}
            scale={[0.2, 0.1, 0.01]}
          />
          <mesh
            name="Cube 728"
            geometry={nodes['Cube 728'].geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[-738.78, -35.93, -681.47]}
            rotation={[-1.37, -0.23, -1.84]}
            scale={[0.2, 0.1, 0.01]}
          />
          <mesh
            name="Cube 7416"
            geometry={nodes['Cube 7416'].geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[682.71, 52.68, -858.54]}
            rotation={[-1.45, -0.26, -2.85]}
            scale={[0.1, 0.05, 0]}
          />
          <mesh
            name="Cube 739"
            geometry={nodes['Cube 739'].geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[661.52, 53.78, -861.69]}
            rotation={[-1.24, 0.3, -0.75]}
            scale={[0.09, 0.05, 0]}
          />
          <mesh
            name="Cube 729"
            geometry={nodes['Cube 729'].geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[668.78, 50.33, -842.59]}
            rotation={[-1.71, -0.08, 1.45]}
            scale={[0.1, 0.05, 0]}
          />
          <mesh
            name="Cube 7417"
            geometry={nodes['Cube 7417'].geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[527.16, -36.69, -253.42]}
            rotation={[-1.58, -0.25, 2.89]}
            scale={[0.19, 0.1, 0.01]}
          />
          <mesh
            name="Cube 7310"
            geometry={nodes['Cube 7310'].geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[500.19, -29.03, -286.16]}
            rotation={[-1.12, 0.19, -1.4]}
            scale={[0.21, 0.09, 0.01]}
          />
          <mesh
            name="Cube 7210"
            geometry={nodes['Cube 7210'].geometry}
            material={materials.plants}
            castShadow
            receiveShadow
            position={[490.65, -39.72, -242.61]}
            rotation={[-1.73, 0.16, 0.92]}
            scale={[0.2, 0.09, 0.01]}
          />
        </group>
        <mesh
          name="fire"
          geometry={nodes.fire.geometry}
          material={materials['fire Material']}
          castShadow
          receiveShadow
          position={[-626.94, 102.42, 1278.69]}
          rotation={[Math.PI, 1.54, 3.13]}
          scale={0.02}
        />
        <mesh
          name="Cube 59"
          geometry={nodes['Cube 59'].geometry}
          material={materials.gem}
          castShadow
          receiveShadow
          position={[-679.23, -243.4, 1310.76]}
          rotation={[-0.08, -0.06, -0.07]}
          scale={[0.06, 0.08, 0.05]}
        />
        <mesh
          name="Cube 58"
          geometry={nodes['Cube 58'].geometry}
          material={materials.gem}
          castShadow
          receiveShadow
          position={[-447.15, -719.32, 1064.2]}
          rotation={[-0.12, -0.09, -0.06]}
          scale={[0.04, 0.06, 0.03]}
        />
        <mesh
          name="Cube 57"
          geometry={nodes['Cube 57'].geometry}
          material={materials.gem}
          castShadow
          receiveShadow
          position={[-629.29, -641.71, 784.57]}
          rotation={[0.18, -0.06, -0.32]}
          scale={0.04}
        />
        <mesh
          name="Cube 60"
          geometry={nodes['Cube 60'].geometry}
          material={materials.gem}
          castShadow
          receiveShadow
          position={[-391.54, -263.57, 1474.88]}
          rotation={[0.42, 0, -0.02]}
          scale={[0.27, 0.19, 0.17]}
        />
        <mesh
          name="Cube 33"
          geometry={nodes['Cube 33'].geometry}
          material={materials.gem}
          castShadow
          receiveShadow
          position={[0.65, -208.33, 1023.74]}
          rotation={[-0.31, -0.53, -0.56]}
          scale={[0.17, 0.19, 0.17]}
        />
        <mesh
          name="floor"
          geometry={nodes.floor.geometry}
          material={materials.gem}
          castShadow
          receiveShadow
          position={[-437.9, -313.58, 1078.92]}
          scale={[2.21, 0.35, 2.22]}
        />
        {/* <OrthographicCamera
          name="1"
          makeDefault={true}
          zoom={0.66}
          far={100000}
          near={-100000}
          position={[-137.76, 254.34, -271.35]}
          rotation={[-2.85, 0.05, 3.13]}
        /> */}
        {/* <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" position={[0, 1, 0]} /> */}
      </group>
    </>
  )
}
