/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera } from '@react-three/drei'
import { useRef } from 'react'
import { useFrame } from '@react-three/fiber';

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/A2WjjMoc1L4vzII6/scene.splinecode')
  const ref = useRef();
  useFrame(() => {
    ref.current.rotation.y += 0.002
  })  
  return (
    <>
      <color attach="background" args={['#4b4d52']}  />
      <group ref={ref} {...props} dispose={null} position={[0 ,-2, -1]} scale={.03}> 
        <group name="Crystals">
          <mesh
            name="Cube"
            geometry={nodes.Cube.geometry}
            material={nodes.Cube.material}
            castShadow
            receiveShadow
            position={[-39.92, 18.02, 0]}
            rotation={[-Math.PI / 2, 0, -0.85]}
            scale={3.47}
          />
          <mesh
            name="main_planet"
            geometry={nodes.main_planet.geometry}
            material={nodes.main_planet.material}
            castShadow
            receiveShadow
            rotation={[-Math.PI / 2, 0, -0.85]}
            scale={100}
          />
          <mesh
            name="main_crystal"
            geometry={nodes.main_crystal.geometry}
            material={nodes.main_crystal.material}
            castShadow
            receiveShadow
            position={[3.53, 19.09, 1.79]}
            rotation={[-Math.PI / 2, 0, -0.85]}
            scale={9.08}
          />
          <mesh
            name="saturn"
            geometry={nodes.saturn.geometry}
            material={nodes.saturn.material}
            castShadow
            receiveShadow
            position={[21.56, 93.39, -201.54]}
            rotation={[-Math.PI / 2, 0, -0.35]}
            scale={34.58}
          >
            <mesh
              name="saturn1"
              geometry={nodes.saturn1.geometry}
              material={nodes.saturn1.material}
              castShadow
              receiveShadow
            />
          </mesh>
          <mesh
            name="Sphere002"
            geometry={nodes.Sphere002.geometry}
            material={nodes.Sphere002.material}
            castShadow
            receiveShadow
            position={[0, 130.37, 141.13]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={34.58}
          />
          <mesh
            name="tree_planet"
            geometry={nodes.tree_planet.geometry}
            material={nodes.tree_planet.material}
            castShadow
            receiveShadow
            position={[-227.31, 34.29, -119.29]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            name="small_rocks"
            geometry={nodes.small_rocks.geometry}
            material={nodes.small_rocks.material}
            castShadow
            receiveShadow
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            name="Cube002"
            geometry={nodes.Cube002.geometry}
            material={nodes.Cube002.material}
            castShadow
            receiveShadow
            position={[85.16, 13.05, -31.46]}
            rotation={[-0.73, 0.62, -1.85]}
            scale={2.31}
          />
          <mesh
            name="Cube004"
            geometry={nodes.Cube004.geometry}
            material={nodes.Cube004.material}
            castShadow
            receiveShadow
            position={[44.21, -56.71, -25.81]}
            rotation={[0.18, 0.46, -1.98]}
            scale={0.26}
          />
          <mesh
            name="Cube005"
            geometry={nodes.Cube005.geometry}
            material={nodes.Cube005.material}
            castShadow
            receiveShadow
            position={[36.21, -61.89, 25.34]}
            rotation={[-0.63, -0.75, -3.12]}
            scale={3.07}
          />
          <mesh
            name="Cube006"
            geometry={nodes.Cube006.geometry}
            material={nodes.Cube006.material}
            castShadow
            receiveShadow
            position={[7.06, -51.56, 48.36]}
            rotation={[0.76, -1.03, -1.78]}
            scale={0.94}
          />
          <mesh
            name="Cube007"
            geometry={nodes.Cube007.geometry}
            material={nodes.Cube007.material}
            castShadow
            receiveShadow
            position={[5.45, -7.65, 72.88]}
            rotation={[-3.07, -1.29, 1.63]}
            scale={2.8}
          />
          <mesh
            name="Cube008"
            geometry={nodes.Cube008.geometry}
            material={nodes.Cube008.material}
            castShadow
            receiveShadow
            position={[-11.79, -76.73, 17.37]}
            rotation={[2.21, -1.28, 0.22]}
            scale={3.23}
          />
          <mesh
            name="Cube009"
            geometry={nodes.Cube009.geometry}
            material={nodes.Cube009.material}
            castShadow
            receiveShadow
            position={[-43.98, -0.9, 60.24]}
            rotation={[-2.94, -0.72, 1.05]}
            scale={1.14}
          />
          <mesh
            name="Cube010"
            geometry={nodes.Cube010.geometry}
            material={nodes.Cube010.material}
            castShadow
            receiveShadow
            position={[-62.89, -37.03, 15.71]}
            rotation={[2.81, -0.45, 0.7]}
            scale={1.21}
          />
          <mesh
            name="Cube011"
            geometry={nodes.Cube011.geometry}
            material={nodes.Cube011.material}
            castShadow
            receiveShadow
            position={[-75.24, 2.92, -3.34]}
            rotation={[2.97, -0.15, 0.8]}
            scale={1.3}
          />
          <mesh
            name="Cube012"
            geometry={nodes.Cube012.geometry}
            material={nodes.Cube012.material}
            castShadow
            receiveShadow
            position={[-64.07, -55.76, -3.77]}
            rotation={[2.72, -0.2, 0.67]}
            scale={2.58}
          />
          <mesh
            name="Cube013"
            geometry={nodes.Cube013.geometry}
            material={nodes.Cube013.material}
            castShadow
            receiveShadow
            position={[-58.72, 19.4, 18.92]}
            rotation={[0, -1.23, 0.01]}
            scale={3.23}
          />
          <mesh
            name="Cube014"
            geometry={nodes.Cube014.geometry}
            material={nodes.Cube014.material}
            castShadow
            receiveShadow
            position={[-55.65, -10.96, -37.3]}
            rotation={[-2.65, 1.19, 0.78]}
            scale={0.37}
          />
          <mesh
            name="Cube015"
            geometry={nodes.Cube015.geometry}
            material={nodes.Cube015.material}
            castShadow
            receiveShadow
            position={[-30.56, -69.09, -27.04]}
            rotation={[-2.45, 0.92, 0.26]}
            scale={1.96}
          />
          <mesh
            name="Cube016"
            geometry={nodes.Cube016.geometry}
            material={nodes.Cube016.material}
            castShadow
            receiveShadow
            position={[-18.57, 18.85, -85.71]}
            rotation={[-0.51, 0.18, 0.09]}
            scale={2.33}
          />
          <mesh
            name="Cube017"
            geometry={nodes.Cube017.geometry}
            material={nodes.Cube017.material}
            castShadow
            receiveShadow
            position={[-26.65, -65.9, -34.78]}
            rotation={[3.12, 0.87, 1.19]}
            scale={2.45}
          />
          <mesh
            name="Cube018"
            geometry={nodes.Cube018.geometry}
            material={nodes.Cube018.material}
            castShadow
            receiveShadow
            position={[-29.75, 19.5, -47.73]}
            rotation={[0, -0.33, 0]}
            scale={0.02}
          />
          <mesh
            name="Cube019"
            geometry={nodes.Cube019.geometry}
            material={nodes.Cube019.material}
            castShadow
            receiveShadow
            position={[-11.03, 19.5, -14.84]}
            rotation={[0, -0.63, 0]}
            scale={2.24}
          />
          <mesh
            name="Cube020"
            geometry={nodes.Cube020.geometry}
            material={nodes.Cube020.material}
            castShadow
            receiveShadow
            position={[-39.4, 4.01, -62.55]}
            rotation={[3.05, 0.89, 0.84]}
            scale={2.89}
          />
          <mesh
            name="Cube021"
            geometry={nodes.Cube021.geometry}
            material={nodes.Cube021.material}
            castShadow
            receiveShadow
            position={[-9.33, 19.29, 81.48]}
            rotation={[0.02, -0.48, -0.01]}
            scale={0.72}
          />
          <mesh
            name="Cube022"
            geometry={nodes.Cube022.geometry}
            material={nodes.Cube022.material}
            castShadow
            receiveShadow
            position={[22.37, 19.4, 37.56]}
            rotation={[0.01, -0.7, 0]}
            scale={1.41}
          />
          <mesh
            name="Cube023"
            geometry={nodes.Cube023.geometry}
            material={nodes.Cube023.material}
            castShadow
            receiveShadow
            position={[15.75, 17.09, 89.08]}
            rotation={[1.05, -0.39, -0.14]}
            scale={1.83}
          />
          <mesh
            name="Cube024"
            geometry={nodes.Cube024.geometry}
            material={nodes.Cube024.material}
            castShadow
            receiveShadow
            position={[-5.11, 19.49, -52.03]}
            rotation={[0, -0.24, 0]}
            scale={2.2}
          />
          <mesh
            name="Cube025"
            geometry={nodes.Cube025.geometry}
            material={nodes.Cube025.material}
            castShadow
            receiveShadow
            position={[15.67, 19.37, -18.39]}
            rotation={[-0.02, -0.51, -0.02]}
            scale={1.42}
          />
          <mesh
            name="Cube026"
            geometry={nodes.Cube026.geometry}
            material={nodes.Cube026.material}
            castShadow
            receiveShadow
            position={[4.28, 19.49, -5.85]}
            rotation={[0, -0.65, 0]}
            scale={3.42}
          />
          <mesh
            name="Cube027"
            geometry={nodes.Cube027.geometry}
            material={nodes.Cube027.material}
            castShadow
            receiveShadow
            position={[25.71, 19.01, -28.49]}
            rotation={[-0.03, -0.43, -0.04]}
            scale={1.23}
          />
          <mesh
            name="Cube028"
            geometry={nodes.Cube028.geometry}
            material={nodes.Cube028.material}
            castShadow
            receiveShadow
            position={[64.21, 17.21, -47.12]}
            rotation={[-0.01, -0.52, -0.02]}
            scale={0.96}
          />
          <mesh
            name="Cube029"
            geometry={nodes.Cube029.geometry}
            material={nodes.Cube029.material}
            castShadow
            receiveShadow
            position={[59, 19.5, 37.84]}
            rotation={[0, -0.66, 0]}
            scale={1.24}
          />
          <mesh
            name="Cube030"
            geometry={nodes.Cube030.geometry}
            material={nodes.Cube030.material}
            castShadow
            receiveShadow
            position={[15.69, -63.63, -35.38]}
            rotation={[-0.19, 0.91, -2.18]}
            scale={0.11}
          />
          <mesh
            name="Cube031"
            geometry={nodes.Cube031.geometry}
            material={nodes.Cube031.material}
            castShadow
            receiveShadow
            position={[48.24, -8.78, -49.98]}
            rotation={[0.15, 1.14, -1.85]}
            scale={0.57}
          />
          <mesh
            name="Cube032"
            geometry={nodes.Cube032.geometry}
            material={nodes.Cube032.material}
            castShadow
            receiveShadow
            position={[58.87, 0.5, -51.41]}
            rotation={[0.22, 0.93, -2.5]}
            scale={1.99}
          />
          <mesh
            name="Cube033"
            geometry={nodes.Cube033.geometry}
            material={nodes.Cube033.material}
            castShadow
            receiveShadow
            position={[-2.9, -72.15, 10.34]}
            rotation={[1.16, -0.47, -1.49]}
            scale={1.77}
          />
          <mesh
            name="Cube034"
            geometry={nodes.Cube034.geometry}
            material={nodes.Cube034.material}
            castShadow
            receiveShadow
            position={[85.16, 13.05, -31.46]}
            rotation={[-0.73, 0.62, -1.85]}
            scale={2.31}
          />
          <mesh
            name="Cube035"
            geometry={nodes.Cube035.geometry}
            material={nodes.Cube035.material}
            castShadow
            receiveShadow
            position={[44.21, -56.71, -25.81]}
            rotation={[0.18, 0.46, -1.98]}
            scale={0.26}
          />
          <mesh
            name="Cube036"
            geometry={nodes.Cube036.geometry}
            material={nodes.Cube036.material}
            castShadow
            receiveShadow
            position={[36.21, -61.89, 25.34]}
            rotation={[-0.63, -0.75, -3.12]}
            scale={3.07}
          />
          <mesh
            name="Cube037"
            geometry={nodes.Cube037.geometry}
            material={nodes.Cube037.material}
            castShadow
            receiveShadow
            position={[7.06, -51.56, 48.36]}
            rotation={[0.76, -1.03, -1.78]}
            scale={0.94}
          />
          <mesh
            name="Cube038"
            geometry={nodes.Cube038.geometry}
            material={nodes.Cube038.material}
            castShadow
            receiveShadow
            position={[5.45, -7.65, 72.88]}
            rotation={[-3.07, -1.29, 1.63]}
            scale={2.8}
          />
          <mesh
            name="Cube039"
            geometry={nodes.Cube039.geometry}
            material={nodes.Cube039.material}
            castShadow
            receiveShadow
            position={[-11.79, -76.73, 17.37]}
            rotation={[2.21, -1.28, 0.22]}
            scale={3.23}
          />
          <mesh
            name="Cube040"
            geometry={nodes.Cube040.geometry}
            material={nodes.Cube040.material}
            castShadow
            receiveShadow
            position={[-43.98, -0.9, 60.24]}
            rotation={[-2.94, -0.72, 1.05]}
            scale={1.14}
          />
          <mesh
            name="Cube041"
            geometry={nodes.Cube041.geometry}
            material={nodes.Cube041.material}
            castShadow
            receiveShadow
            position={[-62.89, -37.03, 15.71]}
            rotation={[2.81, -0.45, 0.7]}
            scale={1.21}
          />
          <mesh
            name="Cube042"
            geometry={nodes.Cube042.geometry}
            material={nodes.Cube042.material}
            castShadow
            receiveShadow
            position={[-75.24, 2.92, -3.34]}
            rotation={[2.97, -0.15, 0.8]}
            scale={1.3}
          />
          <mesh
            name="Cube043"
            geometry={nodes.Cube043.geometry}
            material={nodes.Cube043.material}
            castShadow
            receiveShadow
            position={[-64.07, -55.76, -3.77]}
            rotation={[2.72, -0.2, 0.67]}
            scale={2.58}
          />
          <mesh
            name="Cube044"
            geometry={nodes.Cube044.geometry}
            material={nodes.Cube044.material}
            castShadow
            receiveShadow
            position={[-58.72, 19.4, 18.92]}
            rotation={[0, -1.23, 0.01]}
            scale={3.23}
          />
          <mesh
            name="Cube045"
            geometry={nodes.Cube045.geometry}
            material={nodes.Cube045.material}
            castShadow
            receiveShadow
            position={[-55.65, -10.96, -37.3]}
            rotation={[-2.65, 1.19, 0.78]}
            scale={0.37}
          />
          <mesh
            name="Cube046"
            geometry={nodes.Cube046.geometry}
            material={nodes.Cube046.material}
            castShadow
            receiveShadow
            position={[-30.56, -69.09, -27.04]}
            rotation={[-2.45, 0.92, 0.26]}
            scale={1.96}
          />
          <mesh
            name="Cube047"
            geometry={nodes.Cube047.geometry}
            material={nodes.Cube047.material}
            castShadow
            receiveShadow
            position={[-18.57, 18.85, -85.71]}
            rotation={[-0.51, 0.18, 0.09]}
            scale={2.33}
          />
          <mesh
            name="Cube048"
            geometry={nodes.Cube048.geometry}
            material={nodes.Cube048.material}
            castShadow
            receiveShadow
            position={[-26.65, -65.9, -34.78]}
            rotation={[3.12, 0.87, 1.19]}
            scale={2.45}
          />
          <mesh
            name="Cube049"
            geometry={nodes.Cube049.geometry}
            material={nodes.Cube049.material}
            castShadow
            receiveShadow
            position={[-29.75, 19.5, -47.73]}
            rotation={[0, -0.33, 0]}
            scale={0.02}
          />
          <mesh
            name="Cube050"
            geometry={nodes.Cube050.geometry}
            material={nodes.Cube050.material}
            castShadow
            receiveShadow
            position={[-11.03, 19.5, -14.84]}
            rotation={[0, -0.63, 0]}
            scale={2.24}
          />
          <mesh
            name="Cube051"
            geometry={nodes.Cube051.geometry}
            material={nodes.Cube051.material}
            castShadow
            receiveShadow
            position={[-39.4, 4.01, -62.55]}
            rotation={[3.05, 0.89, 0.84]}
            scale={2.89}
          />
          <mesh
            name="Cube052"
            geometry={nodes.Cube052.geometry}
            material={nodes.Cube052.material}
            castShadow
            receiveShadow
            position={[-9.33, 19.29, 81.48]}
            rotation={[0.02, -0.48, -0.01]}
            scale={0.72}
          />
          <mesh
            name="Cube053"
            geometry={nodes.Cube053.geometry}
            material={nodes.Cube053.material}
            castShadow
            receiveShadow
            position={[22.37, 19.4, 37.56]}
            rotation={[0.01, -0.7, 0]}
            scale={1.41}
          />
          <mesh
            name="Cube054"
            geometry={nodes.Cube054.geometry}
            material={nodes.Cube054.material}
            castShadow
            receiveShadow
            position={[15.75, 17.09, 89.08]}
            rotation={[1.05, -0.39, -0.14]}
            scale={1.83}
          />
          <mesh
            name="Cube055"
            geometry={nodes.Cube055.geometry}
            material={nodes.Cube055.material}
            castShadow
            receiveShadow
            position={[-5.11, 19.49, -52.03]}
            rotation={[0, -0.24, 0]}
            scale={2.2}
          />
          <mesh
            name="Cube056"
            geometry={nodes.Cube056.geometry}
            material={nodes.Cube056.material}
            castShadow
            receiveShadow
            position={[15.67, 19.37, -18.39]}
            rotation={[-0.02, -0.51, -0.02]}
            scale={1.42}
          />
          <mesh
            name="Cube057"
            geometry={nodes.Cube057.geometry}
            material={nodes.Cube057.material}
            castShadow
            receiveShadow
            position={[4.28, 19.49, -5.85]}
            rotation={[0, -0.65, 0]}
            scale={3.42}
          />
          <mesh
            name="Cube058"
            geometry={nodes.Cube058.geometry}
            material={nodes.Cube058.material}
            castShadow
            receiveShadow
            position={[25.71, 19.01, -28.49]}
            rotation={[-0.03, -0.43, -0.04]}
            scale={1.23}
          />
          <mesh
            name="Cube059"
            geometry={nodes.Cube059.geometry}
            material={nodes.Cube059.material}
            castShadow
            receiveShadow
            position={[64.21, 17.21, -47.12]}
            rotation={[-0.01, -0.52, -0.02]}
            scale={0.96}
          />
          <mesh
            name="Cube060"
            geometry={nodes.Cube060.geometry}
            material={nodes.Cube060.material}
            castShadow
            receiveShadow
            position={[59, 19.5, 37.84]}
            rotation={[0, -0.66, 0]}
            scale={1.24}
          />
          <mesh
            name="Cube061"
            geometry={nodes.Cube061.geometry}
            material={nodes.Cube061.material}
            castShadow
            receiveShadow
            position={[15.69, -63.63, -35.38]}
            rotation={[-0.19, 0.91, -2.18]}
            scale={0.11}
          />
          <mesh
            name="Cube062"
            geometry={nodes.Cube062.geometry}
            material={nodes.Cube062.material}
            castShadow
            receiveShadow
            position={[48.24, -8.78, -49.98]}
            rotation={[0.15, 1.14, -1.85]}
            scale={0.57}
          />
          <mesh
            name="Cube063"
            geometry={nodes.Cube063.geometry}
            material={nodes.Cube063.material}
            castShadow
            receiveShadow
            position={[58.87, 0.5, -51.41]}
            rotation={[0.22, 0.93, -2.5]}
            scale={1.99}
          />
          <mesh
            name="Cube064"
            geometry={nodes.Cube064.geometry}
            material={nodes.Cube064.material}
            castShadow
            receiveShadow
            position={[-2.9, -72.15, 10.34]}
            rotation={[1.16, -0.47, -1.49]}
            scale={1.77}
          />
          <mesh
            name="Cube065"
            geometry={nodes.Cube065.geometry}
            material={nodes.Cube065.material}
            castShadow
            receiveShadow
            position={[6.22, 129.58, 107.24]}
            rotation={[0.01, 1.39, -1.6]}
            scale={2.31}
          />
          <mesh
            name="Cube066"
            geometry={nodes.Cube066.geometry}
            material={nodes.Cube066.material}
            castShadow
            receiveShadow
            position={[5.55, 157.25, 120.46]}
            rotation={[-0.19, 1.22, -0.5]}
            scale={0.26}
          />
          <mesh
            name="Cube067"
            geometry={nodes.Cube067.geometry}
            material={nodes.Cube067.material}
            castShadow
            receiveShadow
            position={[27.13, 138.29, 121.54]}
            rotation={[-0.01, 0.62, -1.33]}
            scale={3.07}
          />
          <mesh
            name="Cube068"
            geometry={nodes.Cube068.geometry}
            material={nodes.Cube068.material}
            castShadow
            receiveShadow
            position={[23.8, 105.41, 140.79]}
            rotation={[0.01, 0.01, -2.38]}
            scale={0.94}
          />
          <mesh
            name="Cube069"
            geometry={nodes.Cube069.geometry}
            material={nodes.Cube069.material}
            castShadow
            receiveShadow
            position={[32.64, 120.8, 136.84]}
            rotation={[0.04, 0.12, -1.86]}
            scale={2.8}
          />
          <mesh
            name="Cube070"
            geometry={nodes.Cube070.geometry}
            material={nodes.Cube070.material}
            castShadow
            receiveShadow
            position={[29.31, 144.69, 152.05]}
            rotation={[-0.02, -0.36, -1.15]}
            scale={3.23}
          />
          <mesh
            name="Cube071"
            geometry={nodes.Cube071.geometry}
            material={nodes.Cube071.material}
            castShadow
            receiveShadow
            position={[29.87, 142.84, 152.98]}
            rotation={[0, -0.38, -1.2]}
            scale={1.14}
          />
          <mesh
            name="Cube072"
            geometry={nodes.Cube072.geometry}
            material={nodes.Cube072.material}
            castShadow
            receiveShadow
            position={[26.11, 120.8, 161.17]}
            rotation={[0.05, -0.66, -1.82]}
            scale={1.21}
          />
          <mesh
            name="Cube073"
            geometry={nodes.Cube073.geometry}
            material={nodes.Cube073.material}
            castShadow
            receiveShadow
            position={[14.74, 106.87, 161.52]}
            rotation={[0.03, -0.96, -2.29]}
            scale={1.3}
          />
          <mesh
            name="Cube074"
            geometry={nodes.Cube074.geometry}
            material={nodes.Cube074.material}
            castShadow
            receiveShadow
            position={[18.25, 142.84, 167.58]}
            rotation={[-0.01, -0.97, -1.21]}
            scale={2.58}
          />
          <mesh
            name="Cube075"
            geometry={nodes.Cube075.geometry}
            material={nodes.Cube075.material}
            castShadow
            receiveShadow
            position={[2.05, 160.93, 156.77]}
            rotation={[-1.08, -1.51, -1.56]}
            scale={3.23}
          />
          <mesh
            name="Cube076"
            geometry={nodes.Cube076.geometry}
            material={nodes.Cube076.material}
            castShadow
            receiveShadow
            position={[-5.34, 138.29, 174.17]}
            rotation={[-3.08, -1.41, 1.86]}
            scale={0.37}
          />
          <mesh
            name="Cube077"
            geometry={nodes.Cube077.geometry}
            material={nodes.Cube077.material}
            castShadow
            receiveShadow
            position={[-6.22, 129.58, 175.02]}
            rotation={[3.13, -1.39, 1.54]}
            scale={1.96}
          />
          <mesh
            name="Cube078"
            geometry={nodes.Cube078.geometry}
            material={nodes.Cube078.material}
            castShadow
            receiveShadow
            position={[-15.11, 127.43, 171.75]}
            rotation={[3.11, -1.11, 1.46]}
            scale={2.33}
          />
          <mesh
            name="Cube079"
            geometry={nodes.Cube079.geometry}
            material={nodes.Cube079.material}
            castShadow
            receiveShadow
            position={[-23.11, 124.85, 165.99]}
            rotation={[3.14, -0.82, 1.41]}
            scale={2.45}
          />
          <mesh
            name="Cube080"
            geometry={nodes.Cube080.geometry}
            material={nodes.Cube080.material}
            castShadow
            receiveShadow
            position={[-9.69, 161.95, 151.13]}
            rotation={[-3.13, -0.79, 2.73]}
            scale={0.02}
          />
          <mesh
            name="Cube081"
            geometry={nodes.Cube081.geometry}
            material={nodes.Cube081.material}
            castShadow
            receiveShadow
            position={[-13.44, 104.05, 158.64]}
            rotation={[3.04, -0.84, 0.63]}
            scale={2.24}
          />
          <mesh
            name="Cube082"
            geometry={nodes.Cube082.geometry}
            material={nodes.Cube082.material}
            castShadow
            receiveShadow
            position={[-9.71, 99, 151.59]}
            rotation={[3.12, -0.79, 0.42]}
            scale={2.89}
          />
          <mesh
            name="Cube083"
            geometry={nodes.Cube083.geometry}
            material={nodes.Cube083.material}
            castShadow
            receiveShadow
            position={[-21.86, 105.41, 150.56]}
            rotation={[3.13, -0.4, 0.76]}
            scale={0.72}
          />
          <mesh
            name="Cube084"
            geometry={nodes.Cube084.geometry}
            material={nodes.Cube084.material}
            castShadow
            receiveShadow
            position={[-32.34, 127.43, 152.1]}
            rotation={[3.13, -0.33, 1.48]}
            scale={1.41}
          />
          <mesh
            name="Cube085"
            geometry={nodes.Cube085.geometry}
            material={nodes.Cube085.material}
            castShadow
            receiveShadow
            position={[-32.19, 118.31, 142.31]}
            rotation={[3.13, -0.03, 1.21]}
            scale={1.83}
          />
          <mesh
            name="Cube086"
            geometry={nodes.Cube086.geometry}
            material={nodes.Cube086.material}
            castShadow
            receiveShadow
            position={[-24.92, 154.21, 141.51]}
            rotation={[-3.13, -0.01, 2.33]}
            scale={2.2}
          />
          <mesh
            name="Cube087"
            geometry={nodes.Cube087.geometry}
            material={nodes.Cube087.material}
            castShadow
            receiveShadow
            position={[-22.03, 104.05, 139.68]}
            rotation={[3.08, 0.14, 0.71]}
            scale={1.42}
          />
          <mesh
            name="Cube088"
            geometry={nodes.Cube088.geometry}
            material={nodes.Cube088.material}
            castShadow
            receiveShadow
            position={[-19.85, 102.4, 137.94]}
            rotation={[3.12, 0.18, 0.63]}
            scale={3.42}
          />
          <mesh
            name="Cube089"
            geometry={nodes.Cube089.geometry}
            material={nodes.Cube089.material}
            castShadow
            receiveShadow
            position={[-23.17, 154.21, 131.94]}
            rotation={[-3.13, 0.38, 2.33]}
            scale={1.23}
          />
          <mesh
            name="Cube090"
            geometry={nodes.Cube090.geometry}
            material={nodes.Cube090.material}
            castShadow
            receiveShadow
            position={[-29.52, 120.8, 126.56]}
            rotation={[3.1, 0.47, 1.31]}
            scale={0.96}
          />
          <mesh
            name="Cube091"
            geometry={nodes.Cube091.geometry}
            material={nodes.Cube091.material}
            castShadow
            receiveShadow
            position={[-20.12, 131.59, 113.27]}
            rotation={[-3.14, 0.95, 1.6]}
            scale={1.24}
          />
          <mesh
            name="Cube092"
            geometry={nodes.Cube092.geometry}
            material={nodes.Cube092.material}
            castShadow
            receiveShadow
            position={[-16.01, 110.54, 117.91]}
            rotation={[3.13, 0.97, 0.97]}
            scale={0.11}
          />
          <mesh
            name="Cube093"
            geometry={nodes.Cube093.geometry}
            material={nodes.Cube093.material}
            castShadow
            receiveShadow
            position={[-9.77, 114.53, 112.32]}
            rotation={[2.96, 1.27, 1.27]}
            scale={0.57}
          />
          <mesh
            name="Cube094"
            geometry={nodes.Cube094.geometry}
            material={nodes.Cube094.material}
            castShadow
            receiveShadow
            position={[-0.93, 106.87, 115.99]}
            rotation={[2.45, 1.54, 1.51]}
            scale={1.99}
          />
          <mesh
            name="Cube095"
            geometry={nodes.Cube095.geometry}
            material={nodes.Cube095.material}
            castShadow
            receiveShadow
            position={[-0.48, 142.84, 109]}
            rotation={[-2.85, 1.56, 1.64]}
            scale={1.77}
          />
        </group>
        <directionalLight
          name="Directional Light"
          castShadow
          intensity={0.7}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-near={-10000}
          shadow-camera-far={100000}
          shadow-camera-left={-500}
          shadow-camera-right={500}
          shadow-camera-top={500}
          shadow-camera-bottom={-500}
          position={[200, 300, 300]}
        />
        {/* <OrthographicCamera
          name="1"
          makeDefault={true}
          zoom={2.27}
          far={100000}
          near={-100000}
          position={[904.91, 243.53, -205.8]}
          rotation={[-2.66, 1.23, 2.68]}
        /> */}
        <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" position={[0, 1, 0]} />
      </group>
    </>
  )
}
