import { Suspense, useEffect, useState } from 'react'
import { Canvas } from '@react-three/fiber'
import  { OrbitControls, Preload, useGLTF } from '@react-three/drei'
import CanvasLoader from '../Loader'

/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera } from '@react-three/drei'

const Computers = ({ ...props }) => {
  const { nodes, materials } = useSpline('https://prod.spline.design/A2WjjMoc1L4vzII6/scene.splinecode')
  return (
    <>
      <group {...props}  scale={1}>
        
        <group name="Group 7" position={[-9.5, 45.76, -23.56]}>
          <pointLight
            name="Point Light"
            castShadow
            intensity={1.77}
            distance={350}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-near={100}
            shadow-camera-far={100000}
            color="#b900fe"
            position={[8.5, 153.05, 22.56]}
          />
          <group name="Planet-with-ring" position={[-173.96, 21.24, -164.62]}>
            <mesh
              name="Sphere"
              geometry={nodes.Sphere.geometry}
              material={materials['Sphere Material']}
              castShadow
              receiveShadow
              position={[-0.06, 0, -0.22]}
              rotation={[-0.26, 0.02, 0]}
              scale={1}
            />
            <mesh
              name="saturn"
              geometry={nodes.saturn.geometry}
              material={nodes.saturn.material}
              castShadow
              receiveShadow
              position={[0.01, -2.59, -0.05]}
              rotation={[-Math.PI / 2, 0, -0.35]}
              scale={34.58}
            />
          </group>
          <group name="Set-up" position={[4.1, 35.12, 3.34]}>
            <group name="Lamps" position={[-33.33, 23.23, -14.88]}>
              <pointLight
                name="Point Light 3"
                castShadow
                intensity={3}
                decay={10}
                distance={300}
                shadow-mapSize-width={1024}
                shadow-mapSize-height={1024}
                shadow-camera-near={100}
                shadow-camera-far={100000}
                color="#b9e9fe"
                position={[34.37, -4.59, -39.47]}
              />
              <pointLight
                name="Point Light 2"
                castShadow
                intensity={3}
                decay={10}
                distance={300}
                shadow-mapSize-width={1024}
                shadow-mapSize-height={1024}
                shadow-camera-near={100}
                shadow-camera-far={100000}
                color="#b9e9fe"
                position={[-34.37, -4.59, 39.47]}
              />
              <mesh
                name="Sphere1"
                geometry={nodes.Sphere1.geometry}
                material={materials['Sphere1 Material']}
                castShadow
                receiveShadow
                position={[35.13, -14.8, -38.26]}
                rotation={[0, -0.73, 0]}
                scale={0.24}
              />
              <mesh
                name="Sphere2"
                geometry={nodes.Sphere2.geometry}
                material={materials['Sphere2 Material']}
                castShadow
                receiveShadow
                position={[-35.92, -14.8, 41.23]}
                rotation={[0, -0.73, 0]}
                scale={0.24}
              />
              <mesh
                name="fire"
                geometry={nodes.fire.geometry}
                material={materials['fire Material']}
                castShadow
                receiveShadow
                position={[-34.39, 1.15, 41.41]}
                rotation={[0, 0.87, -0.01]}
                scale={[0, 0.01, 0.01]}
              />
            </group>
            <mesh
              name="Cube 65"
              geometry={nodes['Cube 65'].geometry}
              material={materials['Cube 65 Material']}
              castShadow
              receiveShadow
              position={[-19.85, 3, 0.14]}
              rotation={[0, -0.73, 0]}
              scale={[0.08, 0.08, 0.21]}
            />
            <group name=" Coffee Cup" position={[14.91, 8.32, -40.38]} rotation={[0, -0.73, 0]} scale={0.79}>
              <mesh
                name="Torus"
                geometry={nodes.Torus.geometry}
                material={materials['Torus Material']}
                castShadow
                receiveShadow
                position={[5.04, 0.64, 0.39]}
                rotation={[-Math.PI, 0, -Math.PI]}
                scale={1.46}
              />
              <mesh
                name="Cylinder 11"
                geometry={nodes['Cylinder 11'].geometry}
                material={materials['Cylinder 11 Material']}
                castShadow
                receiveShadow
                position={[-2.75, 0, 0]}
                rotation={[0, Math.PI / 2, 0]}
                scale={[0.35, 0.63, 0.35]}
              />
            </group>
            <group name="picture-ui" position={[-36.58, 30.47, -6.83]} rotation={[0, 0.85, 0]} scale={0.05}>
              <mesh
                name="Triangle 2"
                geometry={nodes['Triangle 2'].geometry}
                material={materials['Triangle 2 Material']}
                castShadow
                receiveShadow
                position={[41.47, -49, 11.47]}
                rotation={[0, 0, 0]}
                scale={[1.16, 1.16, 11432065741406.77]}
              />
              <mesh
                name="Triangle"
                geometry={nodes.Triangle.geometry}
                material={materials['Triangle Material']}
                castShadow
                receiveShadow
                position={[-100.91, -31.31, 10.86]}
                rotation={[0, 0, 0]}
                scale={[1.16, 1.16, 11432065741406.77]}
              />
              <mesh
                name="Ellipse"
                geometry={nodes.Ellipse.geometry}
                material={materials['Ellipse Material']}
                castShadow
                receiveShadow
                position={[-13.53, 63.18, 9.13]}
                scale={1.3}
              />
              <mesh
                name="Rectangle 6"
                geometry={nodes['Rectangle 6'].geometry}
                material={materials['Rectangle 6 Material']}
                castShadow
                receiveShadow
                position={[-38.58, 0, -1.01]}
                scale={0.92}
              />
              <mesh
                name="Rectangle 5"
                geometry={nodes['Rectangle 5'].geometry}
                material={materials['red-2']}
                castShadow
                receiveShadow
                position={[-38, 0, -17.88]}
              />
            </group>
            <group name="color-ui" position={[-54.67, 44.34, 2.47]} rotation={[0, 0.85, 0]} scale={0.05}>
              <mesh
                name="Ellipse 3"
                geometry={nodes['Ellipse 3'].geometry}
                material={materials['red-1']}
                castShadow
                receiveShadow
                position={[-77.52, 313.59, 4.65]}
                scale={0.98}
              />
              <mesh
                name="Ellipse 2"
                geometry={nodes['Ellipse 2'].geometry}
                material={materials['red-1']}
                castShadow
                receiveShadow
                position={[-127.29, 313.59, 4.65]}
                scale={0.98}
              />
              <mesh
                name="Ellipse1"
                geometry={nodes.Ellipse1.geometry}
                material={materials['red-1']}
                castShadow
                receiveShadow
                position={[-178.65, 313.59, 4.65]}
                scale={0.98}
              />
              <mesh
                name="Rectangle 7"
                geometry={nodes['Rectangle 7'].geometry}
                material={materials['ui-color']}
                castShadow
                receiveShadow
                position={[0, -238.94, 4]}
              />
              <mesh
                name="Rectangle 9"
                geometry={nodes['Rectangle 9'].geometry}
                material={materials['red-3']}
                castShadow
                position={[98.23, -16.4, 3.27]}
              />
              <mesh
                name="Rectangle 8"
                geometry={nodes['Rectangle 8'].geometry}
                material={materials['red-3']}
                castShadow
                position={[98.23, 173.68, 3.27]}
              />
              <mesh
                name="Rectangle 91"
                geometry={nodes['Rectangle 91'].geometry}
                material={materials['red-3']}
                castShadow
                position={[-106.76, -16.4, 3.27]}
              />
              <mesh
                name="Rectangle 61"
                geometry={nodes['Rectangle 61'].geometry}
                material={materials['red-2']}
                castShadow
                position={[-106.76, 173.68, 3.27]}
              />
              <mesh
                name="Rectangle 51"
                geometry={nodes['Rectangle 51'].geometry}
                material={materials['Rectangle 51 Material']}
                castShadow
                receiveShadow
                position={[0, 0, -13.47]}
              />
            </group>
            <group name="text-ui" position={[-41.48, 30.82, -21.64]} rotation={[0, 0.85, 0]} scale={0.05}>
              <group name="Group 15" position={[381.08, 121.32, 18.33]} scale={1.01}>
                <mesh
                  name="Cylinder 2"
                  geometry={nodes['Cylinder 2'].geometry}
                  material={materials['Cylinder 2 Material']}
                  castShadow
                  receiveShadow
                  position={[-11.1, 133.57, 0.8]}
                  rotation={[0, 0, -Math.PI / 2]}
                  scale={[1, 1.08, 1]}
                />
                <mesh
                  name="Cylinder"
                  geometry={nodes.Cylinder.geometry}
                  material={materials['Cylinder Material']}
                  castShadow
                  receiveShadow
                  position={[-8.64, -133.57, 0.8]}
                  rotation={[0, 0, Math.PI / 2]}
                  scale={[1, 1.08, 1]}
                />
                <mesh
                  name="Sphere 2"
                  geometry={nodes['Sphere 2'].geometry}
                  material={materials['Sphere 2 Material']}
                  castShadow
                  receiveShadow
                  position={[122.25, 132.87, 0]}
                  rotation={[0, 0, -Math.PI / 2]}
                  scale={1}
                />
                <mesh
                  name="Sphere3"
                  geometry={nodes.Sphere3.geometry}
                  material={materials['Sphere3 Material']}
                  castShadow
                  receiveShadow
                  position={[-141.8, -132.87, 0]}
                  rotation={[0, 0, Math.PI / 2]}
                  scale={1}
                />
                <mesh
                  name="Cylinder 21"
                  geometry={nodes['Cylinder 21'].geometry}
                  material={materials['Cylinder 21 Material']}
                  castShadow
                  receiveShadow
                  position={[123.29, 0.97, 0.8]}
                  rotation={[0, 0, Math.PI]}
                  scale={1}
                />
                <mesh
                  name="Cylinder1"
                  geometry={nodes.Cylinder1.geometry}
                  material={materials['Cylinder1 Material']}
                  castShadow
                  receiveShadow
                  position={[-142.85, -0.97, 0.8]}
                  scale={1}
                />
                <mesh
                  name="Sphere 21"
                  geometry={nodes['Sphere 21'].geometry}
                  material={materials['Sphere 21 Material']}
                  castShadow
                  receiveShadow
                  position={[122.59, -132.87, 0]}
                  rotation={[0, 0, Math.PI]}
                />
                <mesh
                  name="Sphere4"
                  geometry={nodes.Sphere4.geometry}
                  material={materials['Sphere4 Material']}
                  castShadow
                  receiveShadow
                  position={[-142.14, 132.87, 0]}
                />
              </group>
              <mesh
                name="Rectangle 4"
                geometry={nodes['Rectangle 4'].geometry}
                material={materials['red-1']}
                castShadow
                receiveShadow
                position={[369.97, -315.35, 5.68]}
                scale={1.52}
              />
              <mesh
                name="Rectangle 3"
                geometry={nodes['Rectangle 3'].geometry}
                material={materials['red-1']}
                castShadow
                receiveShadow
                position={[369.97, -225.14, 5.68]}
                scale={1.52}
              />
              <mesh
                name="Rectangle 2"
                geometry={nodes['Rectangle 2'].geometry}
                material={materials['red-1']}
                castShadow
                receiveShadow
                position={[410.36, -135.84, 5.68]}
                scale={1.52}
              />
              <group name="Text1" position={[372.71, 159.53, 22.45]} scale={1.52}>
                <mesh
                  name="A"
                  geometry={nodes.A.geometry}
                  material={materials['red-1']}
                  castShadow
                  receiveShadow
                  position={[-77, -67.5, 0]}
                />
                <mesh
                  name="a"
                  geometry={nodes.a.geometry}
                  material={materials['red-1']}
                  castShadow
                  receiveShadow
                  position={[3.91, -67.5, 0]}
                />
              </group>
              <mesh
                name="Rectangle 52"
                geometry={nodes['Rectangle 52'].geometry}
                material={materials['Rectangle 52 Material']}
                castShadow
                position={[-180.73, -40.12, 19.4]}
              />
              <mesh
                name="Rectangle 31"
                geometry={nodes['Rectangle 31'].geometry}
                material={materials['Rectangle 31 Material']}
                castShadow
                receiveShadow
                position={[0, -44, 5.66]}
              />
              <mesh
                name="Rectangle 21"
                geometry={nodes['Rectangle 21'].geometry}
                material={materials['Rectangle 21 Material']}
                castShadow
                receiveShadow
                position={[0, 0, -23.62]}
              />
            </group>
            <group name="artboard-2" position={[69.24, -30.53, -16.02]} rotation={[-0.46, -0.95, -0.34]} scale={0.06}>
              <mesh
                name="Cube 5"
                geometry={nodes['Cube 5'].geometry}
                material={materials['Cube 5 Material']}
                castShadow
                receiveShadow
                position={[-1, 125.37, 14.49]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={1}
              />
              <mesh
                name="Cube 6"
                geometry={nodes['Cube 6'].geometry}
                material={materials['Cube 6 Material']}
                castShadow
                receiveShadow
                position={[2.49, -110.74, -215.13]}
                rotation={[Math.PI / 6, 0, -Math.PI / 2]}
                scale={1}
              />
              <mesh
                name="Cube 4"
                geometry={nodes['Cube 4'].geometry}
                material={materials['Cube 4 Material']}
                castShadow
                receiveShadow
                position={[2.49, -180.05, 19.57]}
                rotation={[0, 0, 0]}
                scale={1}
              />
              <mesh
                name="Cube 3"
                geometry={nodes['Cube 3'].geometry}
                material={materials['Cube 3 Material']}
                castShadow
                receiveShadow
                position={[2.49, 164.41, -19.57]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={1}
              />
              <mesh
                name="Cube 2"
                geometry={nodes['Cube 2'].geometry}
                material={materials['Cube 2 Material']}
                castShadow
                receiveShadow
                position={[118.68, -139.91, -19.57]}
                rotation={[0, 0, -1.4]}
                scale={1}
              />
              <mesh
                name="Cube"
                geometry={nodes.Cube.geometry}
                material={materials['Cube Material']}
                castShadow
                receiveShadow
                position={[-107.2, -134.71, -19.57]}
                rotation={[0, 0, -1.75]}
                scale={1}
              />
            </group>
            <group name="Desktop" position={[-23.36, -28.21, -4.67]} rotation={[0, -0.73, 0]} scale={0.24}>
              <mesh
                name="Cylinder 3"
                geometry={nodes['Cylinder 3'].geometry}
                material={materials.stone_detail}
                castShadow
                receiveShadow
                position={[94.43, -9.22, -227.94]}
                scale={[0.11, 1.97, 0.11]}
              />
              <mesh
                name="Cylinder 31"
                geometry={nodes['Cylinder 31'].geometry}
                material={materials.stone_detail}
                castShadow
                receiveShadow
                position={[-95.92, -9.22, -227.94]}
                scale={[0.11, 1.97, 0.11]}
              />
              <mesh
                name="Cylinder 22"
                geometry={nodes['Cylinder 22'].geometry}
                material={materials.stone_detail}
                castShadow
                receiveShadow
                position={[94.43, -9.22, 225.06]}
                scale={[0.11, 1.97, 0.11]}
              />
              <mesh
                name="Cylinder2"
                geometry={nodes.Cylinder2.geometry}
                material={materials.stone_detail}
                castShadow
                receiveShadow
                position={[-95.92, -9.22, 225.06]}
                scale={[0.11, 1.97, 0.11]}
              />
              <mesh
                name="Cube 61"
                geometry={nodes['Cube 61'].geometry}
                material={materials.stairs}
                castShadow
                receiveShadow
                position={[0, 117.37, 0]}
              />
            </group>
          </group>
          <group name="Chair" position={[35.04, 16.8, 53.55]} rotation={[-Math.PI, -0.88, -Math.PI]} scale={1}>
            <mesh
              name="Cylinder 16"
              geometry={nodes['Cylinder 16'].geometry}
              material={materials.Chair}
              castShadow
              receiveShadow
              position={[-20.37, -32.87, -0.85]}
              rotation={[Math.PI, -1.26, -Math.PI / 2]}
              scale={[0.78, 0.17, 0.78]}
            />
            <mesh
              name="Cylinder 15"
              geometry={nodes['Cylinder 15'].geometry}
              material={materials.Chair}
              castShadow
              receiveShadow
              position={[20.68, -34.71, -0.82]}
              rotation={[0, -0.84, Math.PI / 2]}
              scale={[0.78, 0.17, 0.78]}
            />
            <mesh
              name="Cylinder 14"
              geometry={nodes['Cylinder 14'].geometry}
              material={materials['Chair Base']}
              castShadow
              receiveShadow
              position={[0.6, -34.71, -20.16]}
              rotation={[0, -0.02, Math.PI / 2]}
              scale={[0.78, 0.17, 0.78]}
            />
            <mesh
              name="Cylinder 13"
              geometry={nodes['Cylinder 13'].geometry}
              material={materials['Chair Base']}
              castShadow
              receiveShadow
              position={[-0.1, -34.71, 19.84]}
              rotation={[0, -Math.PI / 9, Math.PI / 2]}
              scale={[0.78, 0.17, 0.78]}
            />
            <mesh
              name="Cube 54"
              geometry={nodes['Cube 54'].geometry}
              material={materials['Chair Base']}
              castShadow
              receiveShadow
              position={[-16.75, -30.59, -0.17]}
              rotation={[-Math.PI / 2, 0, 3.12]}
              scale={[0.05, 0.28, 0.36]}
            />
            <mesh
              name="Cube 53"
              geometry={nodes['Cube 53'].geometry}
              material={materials['Chair Base']}
              castShadow
              receiveShadow
              position={[17.24, -30.59, 0.42]}
              rotation={[-Math.PI / 2, 0, 3.12]}
              scale={[0.05, 0.28, 0.36]}
            />
            <mesh
              name="Cube 52"
              geometry={nodes['Cube 52'].geometry}
              material={materials.stairs}
              castShadow
              receiveShadow
              position={[0.24, -27.52, -0.15]}
              rotation={[-Math.PI / 2, 0, 3.12]}
              scale={[0.36, 0.37, 0.36]}
            />
            <mesh
              name="Cube 56"
              geometry={nodes['Cube 56'].geometry}
              material={materials['Chair Base']}
              castShadow
              receiveShadow
              position={[0.52, -30.19, -16.38]}
              rotation={[-Math.PI / 2, 0, 1.55]}
              scale={[0.36, 0.28, 0.36]}
            />
            <mesh
              name="Cube 55"
              geometry={nodes['Cube 55'].geometry}
              material={materials['Chair Base']}
              castShadow
              receiveShadow
              position={[-0.06, -30.19, 16.68]}
              rotation={[-Math.PI / 2, 0, 1.55]}
              scale={[0.36, 0.28, 0.36]}
            />
            <mesh
              name="Cube 51"
              geometry={nodes['Cube 51'].geometry}
              material={materials.stairs}
              castShadow
              receiveShadow
              position={[0.23, -27.52, 0.13]}
              rotation={[-Math.PI / 2, 0, 1.55]}
              scale={[0.36, 0.28, 0.36]}
            />
            <mesh
              name="Cylinder 12"
              geometry={nodes['Cylinder 12'].geometry}
              material={materials.stairs}
              castShadow
              receiveShadow
              position={[0.07, -17.28, -0.22]}
              rotation={[0, -0.02, Math.PI]}
              scale={[0.13, 0.22, 0.13]}
            />
            <mesh
              name="Cube 50"
              geometry={nodes['Cube 50'].geometry}
              material={materials.Chair}
              castShadow
              receiveShadow
              position={[-0.15, -4.73, -0.21]}
              rotation={[-Math.PI / 2, 0, 1.55]}
              scale={[1.37, 1.37, 0.62]}
            />
            <mesh
              name="Cube 49"
              geometry={nodes['Cube 49'].geometry}
              material={materials.stairs}
              castShadow
              receiveShadow
              position={[-1.07, 7.13, -19.31]}
              rotation={[0, 1.55, 0]}
            />
            <mesh
              name="Cube 48"
              geometry={nodes['Cube 48'].geometry}
              material={materials.Chair}
              castShadow
              receiveShadow
              position={[-1.08, 26.9, -18.31]}
              rotation={[0, 1.55, 0]}
            />
          </group>
          <mesh
            name="main_planet"
            geometry={nodes.main_planet.geometry}
            material={nodes.main_planet.material}
            castShadow
            receiveShadow
            position={[8.5, -41.76, 22.56]}
            rotation={[-Math.PI / 2, 0, -0.85]}
            scale={100}
          />
          <group name="Group 5" position={[187.81, 76.92, 180.48]}>
            <mesh
              name="Sphere002"
              geometry={nodes.Sphere002.geometry}
              material={nodes.Sphere002.material}
              castShadow
              receiveShadow
              position={[-4.24, 0.26, -2.56]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={34.58}
            />
            <mesh
              name="Cube065"
              geometry={nodes.Cube065.geometry}
              material={nodes.Cube065.material}
              castShadow
              receiveShadow
              position={[1.98, -0.54, -36.45]}
              rotation={[0.01, 1.39, -1.6]}
              scale={2.31}
            />
            <mesh
              name="Cube067"
              geometry={nodes.Cube067.geometry}
              material={nodes.Cube067.material}
              castShadow
              receiveShadow
              position={[22.89, 8.18, -22.15]}
              rotation={[-0.01, 0.62, -1.33]}
              scale={3.07}
            />
            <mesh
              name="Cube068"
              geometry={nodes.Cube068.geometry}
              material={nodes.Cube068.material}
              castShadow
              receiveShadow
              position={[19.56, -24.7, -2.91]}
              rotation={[0.01, 0.01, -2.38]}
              scale={0.94}
            />
            <mesh
              name="Cube069"
              geometry={nodes.Cube069.geometry}
              material={nodes.Cube069.material}
              castShadow
              receiveShadow
              position={[28.4, -9.31, -6.85]}
              rotation={[0.04, 0.12, -1.86]}
              scale={2.8}
            />
            <mesh
              name="Cube070"
              geometry={nodes.Cube070.geometry}
              material={nodes.Cube070.material}
              castShadow
              receiveShadow
              position={[24.36, 14.61, 10.19]}
              rotation={[-0.02, -0.36, -1.15]}
              scale={3.23}
            />
            <mesh
              name="Cube072"
              geometry={nodes.Cube072.geometry}
              material={nodes.Cube072.material}
              castShadow
              receiveShadow
              position={[21.87, -9.31, 17.48]}
              rotation={[0.05, -0.66, -1.82]}
              scale={1.21}
            />
            <mesh
              name="Cube073"
              geometry={nodes.Cube073.geometry}
              material={nodes.Cube073.material}
              castShadow
              receiveShadow
              position={[10.5, -23.25, 17.83]}
              rotation={[0.03, -0.96, -2.29]}
              scale={1.3}
            />
            <mesh
              name="Cube074"
              geometry={nodes.Cube074.geometry}
              material={nodes.Cube074.material}
              castShadow
              receiveShadow
              position={[14.01, 12.73, 23.89]}
              rotation={[-0.01, -0.97, -1.21]}
              scale={2.58}
            />
            <mesh
              name="Cube075"
              geometry={nodes.Cube075.geometry}
              material={nodes.Cube075.material}
              castShadow
              receiveShadow
              position={[-2.19, 30.82, 13.08]}
              rotation={[-1.08, -1.51, -1.56]}
              scale={3.23}
            />
            <mesh
              name="Cube077"
              geometry={nodes.Cube077.geometry}
              material={nodes.Cube077.material}
              castShadow
              receiveShadow
              position={[-10.46, -0.54, 31.33]}
              rotation={[3.13, -1.39, 1.54]}
              scale={1.96}
            />
            <mesh
              name="Cube079"
              geometry={nodes.Cube079.geometry}
              material={nodes.Cube079.material}
              castShadow
              receiveShadow
              position={[-27.35, -5.27, 22.29]}
              rotation={[3.14, -0.82, 1.41]}
              scale={2.45}
            />
            <mesh
              name="Cube080"
              geometry={nodes.Cube080.geometry}
              material={nodes.Cube080.material}
              castShadow
              receiveShadow
              position={[-13.93, 31.83, 7.43]}
              rotation={[-3.13, -0.79, 2.73]}
              scale={0.02}
            />
            <mesh
              name="Cube081"
              geometry={nodes.Cube081.geometry}
              material={nodes.Cube081.material}
              castShadow
              receiveShadow
              position={[-17.68, -26.07, 14.95]}
              rotation={[3.04, -0.84, 0.63]}
              scale={2.24}
            />
            <mesh
              name="Cube082"
              geometry={nodes.Cube082.geometry}
              material={nodes.Cube082.material}
              castShadow
              receiveShadow
              position={[-13.95, -31.11, 7.9]}
              rotation={[3.12, -0.79, 0.42]}
              scale={2.89}
            />
            <mesh
              name="Cube083"
              geometry={nodes.Cube083.geometry}
              material={nodes.Cube083.material}
              castShadow
              receiveShadow
              position={[-26.1, -24.7, 6.87]}
              rotation={[3.13, -0.4, 0.76]}
              scale={0.72}
            />
            <mesh
              name="Cube084"
              geometry={nodes.Cube084.geometry}
              material={nodes.Cube084.material}
              castShadow
              receiveShadow
              position={[-36.58, -2.68, 8.41]}
              rotation={[3.13, -0.33, 1.48]}
              scale={1.41}
            />
            <mesh
              name="Cube085"
              geometry={nodes.Cube085.geometry}
              material={nodes.Cube085.material}
              castShadow
              receiveShadow
              position={[-36.43, -11.8, -1.39]}
              rotation={[3.13, -0.03, 1.21]}
              scale={1.83}
            />
            <mesh
              name="Cube086"
              geometry={nodes.Cube086.geometry}
              material={nodes.Cube086.material}
              castShadow
              receiveShadow
              position={[-29.16, 24.1, -2.18]}
              rotation={[-3.13, -0.01, 2.33]}
              scale={2.2}
            />
            <mesh
              name="Cube088"
              geometry={nodes.Cube088.geometry}
              material={nodes.Cube088.material}
              castShadow
              receiveShadow
              position={[-23.26, -31.31, -8.49]}
              rotation={[3.12, 0.18, 0.63]}
              scale={3.42}
            />
            <mesh
              name="Cube089"
              geometry={nodes.Cube089.geometry}
              material={nodes.Cube089.material}
              castShadow
              receiveShadow
              position={[-27.41, 24.1, -11.75]}
              rotation={[-3.13, 0.38, 2.33]}
              scale={1.23}
            />
            <mesh
              name="Cube090"
              geometry={nodes.Cube090.geometry}
              material={nodes.Cube090.material}
              castShadow
              receiveShadow
              position={[-33.76, -9.31, -17.13]}
              rotation={[3.1, 0.47, 1.31]}
              scale={0.96}
            />
            <mesh
              name="Cube091"
              geometry={nodes.Cube091.geometry}
              material={nodes.Cube091.material}
              castShadow
              receiveShadow
              position={[-24.36, 1.48, -30.42]}
              rotation={[-3.14, 0.95, 1.6]}
              scale={1.24}
            />
            <mesh
              name="Cube094"
              geometry={nodes.Cube094.geometry}
              material={nodes.Cube094.material}
              castShadow
              receiveShadow
              position={[-5.17, -23.25, -27.7]}
              rotation={[2.45, 1.54, 1.51]}
              scale={1.99}
            />
            <mesh
              name="Cube095"
              geometry={nodes.Cube095.geometry}
              material={nodes.Cube095.material}
              castShadow
              receiveShadow
              position={[-4.72, 12.73, -34.7]}
              rotation={[-2.85, 1.56, 1.64]}
              scale={1.77}
            />
          </group>
          <mesh
            name="main_crystal"
            geometry={nodes.main_crystal.geometry}
            material={nodes.main_crystal.material}
            castShadow
            receiveShadow
            position={[-41.13, -22.67, 83.87]}
            rotation={[-Math.PI / 2, 0, -0.85]}
            scale={9.08}
          />
          <mesh
            name="Cube019"
            geometry={nodes.Cube019.geometry}
            material={nodes.Cube019.material}
            castShadow
            receiveShadow
            position={[-49.46, -22.26, -26.75]}
            rotation={[0, -0.63, 0]}
            scale={2.24}
          />
          <mesh
            name="Cube026"
            geometry={nodes.Cube026.geometry}
            material={nodes.Cube026.material}
            castShadow
            receiveShadow
            position={[-10.48, -22.09, 90.08]}
            rotation={[0, -0.65, 0]}
            scale={3.42}
          />
          <mesh
            name="Cube034"
            geometry={nodes.Cube034.geometry}
            material={nodes.Cube034.material}
            castShadow
            receiveShadow
            position={[93.67, -28.71, -8.9]}
            rotation={[-0.73, 0.62, -1.85]}
            scale={2.31}
          />
          <mesh
            name="Cube036"
            geometry={nodes.Cube036.geometry}
            material={nodes.Cube036.material}
            castShadow
            receiveShadow
            position={[44.72, -103.65, 47.9]}
            rotation={[-0.63, -0.75, -3.12]}
            scale={3.07}
          />
          <mesh
            name="Cube038"
            geometry={nodes.Cube038.geometry}
            material={nodes.Cube038.material}
            castShadow
            receiveShadow
            position={[13.96, -49.42, 95.43]}
            rotation={[-3.07, -1.29, 1.63]}
            scale={2.8}
          />
          <mesh
            name="Cube039"
            geometry={nodes.Cube039.geometry}
            material={nodes.Cube039.material}
            castShadow
            receiveShadow
            position={[-3.29, -118.5, 39.93]}
            rotation={[2.21, -1.28, 0.22]}
            scale={3.23}
          />
          <mesh
            name="Cube042"
            geometry={nodes.Cube042.geometry}
            material={nodes.Cube042.material}
            castShadow
            receiveShadow
            position={[-66.74, -38.84, 19.21]}
            rotation={[2.97, -0.15, 0.8]}
            scale={1.3}
          />
          <mesh
            name="Cube043"
            geometry={nodes.Cube043.geometry}
            material={nodes.Cube043.material}
            castShadow
            receiveShadow
            position={[-55.57, -97.52, 18.79]}
            rotation={[2.72, -0.2, 0.67]}
            scale={2.58}
          />
          <mesh
            name="Cube044"
            geometry={nodes.Cube044.geometry}
            material={nodes.Cube044.material}
            castShadow
            receiveShadow
            position={[-50.22, -22.36, 41.48]}
            rotation={[0, -1.23, 0.01]}
            scale={3.23}
          />
          <mesh
            name="Cube046"
            geometry={nodes.Cube046.geometry}
            material={nodes.Cube046.material}
            castShadow
            receiveShadow
            position={[-22.05, -110.85, -4.48]}
            rotation={[-2.45, 0.92, 0.26]}
            scale={1.96}
          />
          <mesh
            name="Cube047"
            geometry={nodes.Cube047.geometry}
            material={nodes.Cube047.material}
            castShadow
            receiveShadow
            position={[-10.06, -22.91, -63.15]}
            rotation={[-0.51, 0.18, 0.09]}
            scale={2.33}
          />
          <mesh
            name="Cube048"
            geometry={nodes.Cube048.geometry}
            material={nodes.Cube048.material}
            castShadow
            receiveShadow
            position={[-18.15, -107.66, -12.22]}
            rotation={[3.12, 0.87, 1.19]}
            scale={2.45}
          />
          <mesh
            name="Cube051"
            geometry={nodes.Cube051.geometry}
            material={nodes.Cube051.material}
            castShadow
            receiveShadow
            position={[-30.89, -37.75, -40]}
            rotation={[3.05, 0.89, 0.84]}
            scale={2.89}
          />
          <mesh
            name="Cube053"
            geometry={nodes.Cube053.geometry}
            material={nodes.Cube053.material}
            castShadow
            receiveShadow
            position={[30.87, -22.36, 60.12]}
            rotation={[0.01, -0.7, 0]}
            scale={1.41}
          />
          <mesh
            name="Cube055"
            geometry={nodes.Cube055.geometry}
            material={nodes.Cube055.material}
            castShadow
            receiveShadow
            position={[3.39, -22.27, -29.48]}
            rotation={[0, -0.24, 0]}
            scale={2.2}
          />
          <mesh
            name="Cube056"
            geometry={nodes.Cube056.geometry}
            material={nodes.Cube056.material}
            castShadow
            receiveShadow
            position={[24.17, -22.39, 4.16]}
            rotation={[-0.02, -0.51, -0.02]}
            scale={1.42}
          />
          <mesh
            name="Cube057"
            geometry={nodes.Cube057.geometry}
            material={nodes.Cube057.material}
            castShadow
            receiveShadow
            position={[79.89, -22.37, 41.35]}
            rotation={[0, -0.65, 0]}
            scale={3.42}
          />
          <mesh
            name="Cube063"
            geometry={nodes.Cube063.geometry}
            material={nodes.Cube063.material}
            castShadow
            receiveShadow
            position={[67.37, -41.26, -28.85]}
            rotation={[0.22, 0.93, -2.5]}
            scale={1.99}
          />
        </group>
        <directionalLight
          name="Directional Light"
          castShadow
          intensity={0.35}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-near={-10000}
          shadow-camera-far={100000}
          shadow-camera-left={-500}
          shadow-camera-right={500}
          shadow-camera-top={500}
          shadow-camera-bottom={-500}
          color="#a0a7e6"
          position={[200, 300, 300]}
        />
        <OrthographicCamera
          name="1"
          makeDefault={true}
          zoom={1.36}
          far={100000}
          near={-100000}
          position={[88.26, 375.22, 836.83]}
          rotation={[-0.37, 0.05, 0.02]}
        />
        <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" />
      </group>
    </>
  )
}



// const Computers = ({ isMobile }) => {
//   const computer = useGLTF('./desktop_pc/scene.gltf')
//   return (
//     <mesh>
//       <hemisphereLight 
//         intensity={0.15}
//         groundColor='black'
//       />
//       <pointLight intensity={1} />
//       <spotLight 
//         position={[-20, 50, 10]}
//         angle={0.12}
//         penumbra={1}
//         castShadow
//         shadow-mapSize={1024}
//       />
//       <primitive 
//         object={computer.scene}
//         scale={isMobile ? 0.65 : 0.75}
//         position={[0, -3.25, -1.5]}
//         rotation={[0, 0.45, 0]}
//       />
//     </mesh>
//   )
// }

const ComputersCanvas = () => {
  const [isMobile, setIsMobile] = useState(false);

  useEffect(() => {
    const mediaQuery = window.matchMedia('(max-width: 500px)')

    setIsMobile(mediaQuery.matches);

    const handleMediaQueryChange = (event) => {
      setIsMobile(event.matches)
    }

    mediaQuery.addEventListener('change', handleMediaQueryChange);

    return () => {
      mediaQuery.removeEventListener('change', handleMediaQueryChange);
    }
  }, [])

  return (
    <Canvas
      shadows flat linear
    >
      <Suspense fallback={<CanvasLoader />}>
        <OrbitControls
          autoRotate
          enableZoom={false}
          // maxPolarAngle={Math.PI / 2}
          // minPolarAngle={Math.PI / 2}
        />
          <Computers position={[0, -90, 0]} isMobile={isMobile}/>
      </Suspense>

      <Preload all/>
    </Canvas>
  )
}

export default ComputersCanvas